version: "3"

services:

  web:
    build: ./menu
    command: sh -c "chmod +x bin/init.sh && bin/init.sh && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./menu:/usr/src/menu